export const FETCH_STORY = "FETCH_STORY";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const UPDATE_CHOICES = "UPDATE_CHOICES";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const CHANGE_DISPLAY = "CHANGE_DISPLAY";
export const CHANGE_LIGHT = "CHANGE_LIGHT";
